// timeBasedImages.js
// Time-based image/message data for Solar System Flower

const timeBasedImages = {
    morning: { // 5h-6h: dậy và ăn sáng
        start: 5,
        end: 6,
        name: "Buổi Sáng - Thức Dậy",
        messages: [{
                text: ["Embe ngủ ngon hơm",
                    "Bạn nhỏ có mệt hơmmm",
                    "Anh nàyyyyy",
                    "Em có nóng hommmm",
                    "Em có mơ đep hơmmm",
                ],
                image: ["images/goodmorningebe.jpg",
                    "images/omm/1.jpg",
                    "images/omm/4.jpg",
                    "images/omm/abbb.gif",
                ]
            },
            {
                text: ["Em nạp nooo nha",
                    "Bạn nhỏ nhớ ăn sáng nha"
                ],
                image: ["images/eat/1.jpg",
                    "images/eat/2.jpg",
                    "images/eat/3.jpg",
                    "images/omm/abbb.gif"
                ]
            },
            {
                text: [
                    "Cha dooooo",
                    "Bạn nhỏ cố gắng nhaaaa",
                    "Anh cầu nguyện cho bạn nhỏ nàyyyyyy",
                    "Anh nhớ bạn nhỏ lắm lắm lắm",
                    "Embe cố gắng nhaaaa",
                    "Anh thương bạn nhỏ nàyyyyy",
                    "Anh nàyyyy",
                    "    "
                ],
                image: ["images/omm/1.jpg",
                    "images/omm/2.jpg",
                    "images/omm/3.jpg",
                    "images/omm/4.jpg",
                    "images/anui/1.jpg",
                    "images/anui/2.jpg",
                    "images/anui/3.jpg",
                    "images/anui/4.jpg",
                    "images/vuii/1.jpg",
                    "images/vuii/2.jpg",
                    "images/vuii/3.jpg",
                    "images/vuii/4.jpg",
                    "images/vuii/5.jpg",
                    "images/vuii/6.jpg",
                    "images/vuii/7.jpg",
                    "images/vuii/8.jpg",
                    "images/vuii/9.jpg",
                    "images/vuii/10.jpg",
                    "images/abbb.gif"
                ]
            },
        ]
    },
    study1: { // 6h-9h30: học
        start: 6,
        end: 9.5,
        name: "Học Buổi Sáng",
        messages: [{
                text: ["Embe học vuiiiii",
                    "Bạn nhỏ cha doooo",
                    "Bạn nhỏ có mệt hơmmm",
                    "Anh nàyyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm"
                ],
                image: Array(10).fill([
                    "images/omm/1.jpg",
                    "images/omm/4.jpg",
                    "images/abbb.gif",
                ]).flat()
            },
            {
                text: ["Em nạp nooo chưaaaaa",
                    "Nay em có bỏ bữa khongggg đóooo"
                ],
                image: Array(15).fill([
                    "images/eat/3.jpg",
                    "images/abbb.gif",
                    "images/omm/1.jpg",
                    "images/omm/4.jpg",
                ]).flat()
            },
            {
                text: ["Em học vuiii nhaaa",
                    "Cha dooooo",
                    "Bạn nhỏ cố gắng nhaaaa",
                    "Anh cầu nguyện cho bạn nhỏ nàyyyyyy",
                    "Anh nhớ bạn nhỏ lắm lắm lắm",
                    "Embe cố gắng nhaaaa",
                    "Anh thương bạn nhỏ nàyyyyy",
                    "Anh nàyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",
                    "Em có buồn hommmm",
                ],
                image: [
                    ...Array(5).fill("images/omm/1.jpg"),
                    "images/omm/2.jpg",
                    "images/omm/3.jpg",
                    ...Array(5).fill("images/omm/4.jpg"),
                    "images/anui/1.jpg",
                    "images/anui/2.jpg",
                    "images/anui/3.jpg",
                    "images/anui/4.jpg",
                    "images/vuii/1.jpg",
                    "images/vuii/2.jpg",
                    "images/vuii/3.jpg",
                    "images/vuii/4.jpg",
                    "images/vuii/5.jpg",
                    "images/vuii/6.jpg",
                    "images/vuii/7.jpg",
                    "images/vuii/8.jpg",
                    "images/vuii/9.jpg",
                    "images/vuii/10.jpg",
                    ...Array(5).fill("images/abbb.gif")
                ]
            },
        ]
    },
    lunch: { // 9h30-10h30: ăn trưa
        start: 9.5,
        end: 10.5,
        name: "Ăn Trưa",
        messages: [{
                text: ["Embe học vuiii hơm",
                    "Bạn nhỏ có mệt hơmmm",
                    "Anh nàyyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm"
                ],
                image: Array(10).fill([
                    "images/omm/1.jpg",
                    "images/omm/4.jpg",
                    "images/abbb.gif",
                ]).flat()
            },
            {
                text: ["Em nạp nooo nha",
                    "Bạn nhỏ nhớ ăn gì nhaaaa",
                    "Đừng có bỏ bữa nhaaaaa"
                ],
                image: Array(15).fill([
                    "images/eat/1.jpg",
                    "images/eat/2.jpg",
                    "images/eat/3.jpg",
                    "images/omm/abbb.gif"
                ]).flat()
            },
            {
                text: ["Anh nàyyyy",
                    "Cha dooooo",
                    "Bạn nhỏ cố gắng nhaaaa",
                    "Anh cầu nguyện cho bạn nhỏ nàyyyyyy",
                    "Anh nhớ bạn nhỏ lắm lắm lắm",
                    "Embe cố gắng nhaaaa",
                    "Anh thương bạn nhỏ nàyyyyy",
                    "Anh nàyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",
                    "Em có buồn hommmm",
                    "    "
                ],
                image: [
                    ...Array(10).fill("images/omm/1.jpg"),
                    "images/omm/2.jpg",
                    "images/omm/3.jpg",
                    ...Array(10).fill("images/omm/4.jpg"),
                    "images/anui/1.jpg",
                    "images/anui/2.jpg",
                    "images/anui/3.jpg",
                    "images/anui/4.jpg",
                    "images/vuii/1.jpg",
                    "images/vuii/2.jpg",
                    "images/vuii/3.jpg",
                    "images/vuii/4.jpg",
                    "images/vuii/5.jpg",
                    "images/vuii/6.jpg",
                    "images/vuii/7.jpg",
                    "images/vuii/8.jpg",
                    "images/vuii/9.jpg",
                    "images/vuii/10.jpg",
                    ...Array(10).fill("images/abbb.gif")
                ]
            },
        ]
    },
    nap: { // 10h30-13h30: ngủ trưa
        start: 10.5,
        end: 13.5,
        name: "Ngủ Trưa",
        messages: [{
                text: ["Embe học zuii hơmmmm" * 0.4,
                    "Em có nạp noooo hơmmm",
                    "Em có bỏ bữa hongggg đóooo",
                    "Nhịn ăn anh buồn đóooo",
                    "Em có nóng hommmm",
                    "Embe phại giữ gìn sức khỏe nhaaaa",
                    "Embe đừng buồn nhaaaaa",
                    "Embe đừng khóc nheee",
                    "Embe đừng tủi thân nheee",
                    "Anh ở đây với bạn nhỏ nàyyyyy",
                    "Anh thương bạn nhỏ nàyyyyy",
                ],
                image: Array(13).fill([
                    "images/omm/1.jpg",
                    "images/omm/4.jpg",
                    "images/omm/abbb.gif",
                ]).flat()
            },
            {
                text: ["Anh nàyyyy",
                    "Cha dooooo",
                    "Bạn nhỏ cố gắng nhaaaa",
                    "Anh cầu nguyện cho bạn nhỏ nàyyyyyy",
                    "Anh nhớ bạn nhỏ lắm lắm lắm",
                    "Embe cố gắng nhaaaa",
                    "Anh thương bạn nhỏ nàyyyyy",
                    "Anh nàyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",
                    "Em có buồn hommmm",
                    "Embe đừng buồn nhaaaaa",
                    "Embe đừng khóc nheee",
                    "    "
                ],
                image: [
                    ...Array(15).fill("images/omm/1.jpg"),
                    "images/omm/2.jpg",
                    "images/omm/3.jpg",
                    ...Array(15).fill("images/omm/4.jpg"),
                    "images/anui/1.jpg",
                    "images/anui/2.jpg",
                    "images/anui/3.jpg",
                    "images/anui/4.jpg",
                    "images/vuii/1.jpg",
                    "images/vuii/2.jpg",
                    "images/vuii/3.jpg",
                    "images/vuii/4.jpg",
                    "images/vuii/5.jpg",
                    "images/vuii/6.jpg",
                    "images/vuii/7.jpg",
                    "images/vuii/8.jpg",
                    "images/vuii/9.jpg",
                    "images/vuii/10.jpg",
                    ...Array(15).fill("images/abbb.gif")
                ]
            },
            {
                text: ["Bạn nhỏ ngủ ngoan nhaaaa",
                    "Embe mơ đẹppppp",
                    "Sleep tightttt",
                    "Dream sweetttt",
                    "Embe ngủ ngoannnn",
                    "    " * 0.3
                ],
                image: Array(12).fill([
                    "images/sleep/1.jpg",
                    "images/sleep/2.jpg",
                    "images/sleep/3.jpg",
                    "images/sleep/4.jpg",
                    "images/sleep/5.jpg",
                    "images/sleep/6.jpg",
                    "images/sleep/7.jpg",
                    "images/sleep/8.jpg",
                    "images/sleep/9.jpg",
                    "images/sleep/10.jpg",
                ]).flat()
            },
        ]
    },
    study2: { // 13h30-16h: học
        start: 13.5,
        end: 16,
        name: "Học Buổi Chiều",
        messages: [{
                text: ["Embe ngủ ngon hơm",
                    "Em có mơ đẹp hơmmm",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",

                ],
                image: [
                    "images/omm/1.jpg",
                    "images/omm/4.jpg",
                    "images/abbb.gif",
                ]
            },
            {
                text: ["Em học vuiii nhaaa",
                    "Cha dooooo",
                    "Bạn nhỏ cố gắng nhaaaa",
                    "Anh cầu nguyện cho bạn nhỏ nàyyyyyy",
                    "Anh nhớ bạn nhỏ lắm lắm lắm",
                    "Embe cố gắng nhaaaa",
                    "Anh thương bạn nhỏ nàyyyyy",
                    "Anh nàyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",
                    "Em có buồn hommmm",
                    "    "
                ],
                image: ["images/omm/1.jpg",
                    "images/omm/2.jpg",
                    "images/omm/3.jpg",
                    "images/omm/4.jpg",
                    "images/anui/1.jpg",
                    "images/anui/2.jpg",
                    "images/anui/3.jpg",
                    "images/anui/4.jpg",
                    "images/vuii/1.jpg",
                    "images/vuii/2.jpg",
                    "images/vuii/3.jpg",
                    "images/vuii/4.jpg",
                    "images/vuii/5.jpg",
                    "images/vuii/6.jpg",
                    "images/vuii/7.jpg",
                    "images/vuii/8.jpg",
                    "images/vuii/9.jpg",
                    "images/vuii/10.jpg",
                    "images/abbb.gif"
                ]
            },
        ]
    },
    dinner: { // 16h-17h30: ăn
        start: 16,
        end: 17.5,
        name: "Ăn Tối",
        messages: [{
                text: ["Embe học zuiii hơm",
                    "Bạn nhỏ có mệt hơmmm",
                    "Anh nàyyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",
                    "Embe phại giữ gìn sức khỏe nhaaaa",
                    "Embe đừng buồn nhaaaaa",
                    "Embe đừng khóc nheee",
                ],
                image: Array(5).fill([
                    "images/omm/1.jpg",
                    "images/omm/4.jpg",
                    "images/obbb.gif",
                ]).flat()
            },
            {
                text: ["Em nạp nooo nha",
                    "Bạn nhỏ nhớ nạp đủ nha",
                    "Đừng có bỏ bữa nhaaaaa",
                ],
                image: Array(15).fill([
                    "images/eat/1.jpg",
                    "images/eat/2.jpg",
                    "images/eat/3.jpg",
                    "images/abbb.gif"
                ]).flat()
            },
            {
                text: ["Em học vuiii nhaaa",
                    "Cha dooooo",
                    "Bạn nhỏ cố gắng nhaaaa",
                    "Anh cầu nguyện cho bạn nhỏ nàyyyyyy",
                    "Anh nhớ bạn nhỏ lắm lắm lắm",
                    "Embe cố gắng nhaaaa",
                    "Anh thương bạn nhỏ nàyyyyy",
                    "Anh nàyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",
                    "Em có buồn hommmm",
                    "    "
                ],
                image: ["images/omm/1.jpg",
                    "images/omm/2.jpg",
                    "images/omm/3.jpg",
                    "images/omm/4.jpg",
                    "images/anui/1.jpg",
                    "images/anui/2.jpg",
                    "images/anui/3.jpg",
                    "images/anui/4.jpg",
                    "images/vuii/1.jpg",
                    "images/vuii/2.jpg",
                    "images/vuii/3.jpg",
                    "images/vuii/4.jpg",
                    "images/vuii/5.jpg",
                    "images/vuii/6.jpg",
                    "images/vuii/7.jpg",
                    "images/vuii/8.jpg",
                    "images/vuii/9.jpg",
                    "images/vuii/10.jpg",
                    "images/abbb.gif"
                ]
            },
        ]
    },
    together: { // 17h30-21h: chung
        start: 17.5,
        end: 21,
        name: "Thời Gian Chung",
        messages: [{
                text: ["Embe nạp no hơm",
                    "Bạn nhỏ có mệt hơmmm",
                    "Anh nàyyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",
                    "Nay em có tủi thân hommm",
                    "Anh xin lỗi bạn nhỏooo",
                    "Embe tắm cẩn thận nhaaaa",
                    "Embe phại giữ gìn sức khỏe nhaaaa",
                    "Embe đừng buồn nhaaaaa",
                    "Embe đừng khóc nheee",
                    "Embe đừng tủi thân nheee",
                    "Anh ở đây với bạn nhỏ nàyyyyy",
                    "Anh thương bạn nhỏ nàyyyyy",
                ],
                image: [
                    "images/omm/1.jpg",
                    "images/omm/4.jpg",
                    "images/abbb.gif",
                ]
            },
            {
                text: ["Em có chuyện gì hạ",
                    "Cha dooooo",
                    "Bạn nhỏ cố gắng nhaaaa",
                    "Anh cầu nguyện cho bạn nhỏ nàyyyyyy",
                    "Anh nhớ bạn nhỏ lắm lắm lắm",
                    "Embe cố gắng nhaaaa",
                    "Anh thương bạn nhỏ nàyyyyy",
                    "Anh nàyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",
                    "Em có buồn hommmm",
                    "    "
                ],
                image: ["images/omm/1.jpg",
                    "images/omm/2.jpg",
                    "images/omm/3.jpg",
                    "images/omm/4.jpg",
                    "images/anui/1.jpg",
                    "images/anui/2.jpg",
                    "images/anui/3.jpg",
                    "images/anui/4.jpg",
                    "images/vuii/1.jpg",
                    "images/vuii/2.jpg",
                    "images/vuii/3.jpg",
                    "images/vuii/4.jpg",
                    "images/vuii/5.jpg",
                    "images/vuii/6.jpg",
                    "images/vuii/7.jpg",
                    "images/vuii/8.jpg",
                    "images/vuii/9.jpg",
                    "images/vuii/10.jpg",
                    "images/abbb.gif"
                ]
            },
            {
                text: ["Em học vuiii nhaaa",
                    "Cha dooooo",
                    "Bạn nhỏ cố gắng nhaaaa",
                    "Anh cầu nguyện cho bạn nhỏ nàyyyyyy",
                    "images/omm/abbb.gif",
                    "    "
                ],
                image: ["images/sleep/1.jpg",
                    "images/sleep/2.jpg",
                    "images/sleep/3.jpg",
                    "images/sleep/4.jpg",
                    "images/sleep/5.jpg",
                    "images/sleep/6.jpg",
                    "images/sleep/7.jpg",
                    "images/sleep/8.jpg",
                    "images/sleep/9.jpg",
                    "images/sleep/10.jpg",
                ]
            },
        ]
    },
    sleep: { // 21h-4h: ngủ (qua đêm)
        start: 21,
        end: 28, // 28 = 4h ngày hôm sau
        name: "Ngủ Đêm",
        messages: [{
                text: ["Embe ngủ ngonnn nhaaaa",
                    "Anh nàyyyyy",
                    "Em có nóng hommmm",
                    "Nay em có tủi thân hommm",
                    "Anh xin lỗi bạn nhỏooo",
                    "Embe phại giữ gìn sức khỏe nhaaaa",
                    "Embe đừng buồn nhaaaaa",
                    "Embe đừng khóc nheee",
                    "Embe đừng tủi thân nheee",
                    "Anh ở đây với bạn nhỏ nàyyyyy",
                    "Anh thương bạn nhỏ nàyyyyy",
                ],
                image: [
                    "images/omm/1.jpg",
                    "images/omm/4.jpg",
                    "images/abbb.gif",
                ]
            },
            {
                text: [
                    "Cha dooooo",
                    "Bạn nhỏ cố gắng nhaaaa",
                    "Anh cầu nguyện cho bạn nhỏ nàyyyyyy",
                    "Anh nhớ bạn nhỏ lắm lắm lắm",
                    "Embe cố gắng nhaaaa",
                    "Anh thương bạn nhỏ nàyyyyy",
                    "Anh nàyyyy",
                    "Em có nóng hommmm",
                    "Em có mệt hommmm",
                    "Em có buồn hommmm",
                    "Nay ai bắt nạt ebe của anh hả",
                    "    "
                ],
                image: ["images/omm/1.jpg",
                    "images/omm/2.jpg",
                    "images/omm/3.jpg",
                    "images/omm/4.jpg",
                    "images/anui/1.jpg",
                    "images/anui/2.jpg",
                    "images/anui/3.jpg",
                    "images/anui/4.jpg",
                    "images/vuii/1.jpg",
                    "images/vuii/2.jpg",
                    "images/vuii/3.jpg",
                    "images/vuii/4.jpg",
                    "images/vuii/5.jpg",
                    "images/vuii/6.jpg",
                    "images/vuii/7.jpg",
                    "images/vuii/8.jpg",
                    "images/vuii/9.jpg",
                    "images/vuii/10.jpg",
                    "images/abbb.gif"
                ]
            },
            {
                text: ["Em ngủ ngoannnnnn",
                    "Wishing you have sweet dreamm",
                    "Wishing you have a nice and lovely dreammm",
                    "Wishing you have a good nighttt",
                    "Wishing you have a peaceful nighttt",
                    "Hope you have a good nighttt",
                    "May god bless you with a peaceful nighttt",
                    "Hope the Lord brave you from all bad dreammm",
                    "May the Lord bless you with a peaceful nighttt",
                    "May the Lord bless you with a good nighttt",
                    "May the Lord bless you with a sweet dreammm",
                    "May the Lord bless you with a lovely dreammm",
                    "May the Lord bless you with a nice dreammm",
                    "Bạn nhỏ cụa anh ngủ ngoannn nha",
                    "Embe đừng thức đêm nhaaaaaa",
                    "Nhớ ngủ ngủ nghỉ sớmmmmm"
                ],
                image: Array(15).fill([
                    "images/sleep/1.jpg",
                    "images/sleep/2.jpg",
                    "images/sleep/3.jpg",
                    "images/sleep/4.jpg",
                    "images/sleep/5.jpg",
                    "images/sleep/6.jpg",
                    "images/sleep/7.jpg",
                    "images/sleep/8.jpg",
                    "images/sleep/9.jpg",
                ]).flat()
            },
        ]
    }
};